config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :omniauth_callbacks => 'users/omniauth_callbacks',
    :sessions => 'users/sessions',
    :registrations => 'users/registrations'
   }

  # ログアウト
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # root 'static_pages#home'
  root 'tweets#new'
  get 'static_pages/home'
  get 'static_pages/faq'
  get 'static_pages/about'
  get 'static_pages/delete'
  resources :users, only: [:show]
  resources :tweets
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def faq
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "●●とは") %>
<h1>●●とは</h1>

<%if user_signed_in? %>
<p><%= link_to "マイページ", static_pages_home_path %></p>
<% else%>
<p><%= link_to "ホーム", static_pages_home_path %></p>
<% end %>

app/views/static_pages/delete.html.erb
<% provide(:title, "退会") %>

<div class="center">
  <h3>ついわく を退会します。</h3>
  <h5>また気が向いたらご登録ください。Thank you(^_^)!!</h5>
</div>

<p class="center" id="gohome">
  <%= link_to "退会する", user_registration_path, method: :delete, data: { confirm: "本当に退会しますか?" }, class: "btn btn-info btn-lg" %>
</p>

app/views/static_pages/faq.html.erb
<% provide(:title, "よくある質問") %>
<h5>いやいや、質問なんてまだなんもねーっす！泣</h5>

<%if user_signed_in? %>
<p><%= link_to "マイページへおもどりください", root_path %></p>
<% else%>
<p><%= link_to "ホームへおもどりください", root_path %></p>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, "ホーム") %>

<div class="row center">
  <h3>static_pages#home</h3>
  <p>ホーム画面だお！！(о´∀`о)</p>
  <% if user_signed_in? %>
    <p><%= image_tag current_user.image.sub(/_normal/, ''), id:"user-image" %></p>
    <p><%= link_to "ツイートする", new_tweet_path %></p>


<div class="form-group">
  <%= form_tag('/tweets', method: :post) do %>
    <p><%= text_area_tag :comment, id:"text-area" %></p>
    <div>
      <label><%= radio_button_tag :image, "./app/assets/images/test1.png" %><%= image_tag "icon1.png", id:"icon" %></label>
      <label><%= radio_button_tag :image, "./app/assets/images/test2.png" %><%= image_tag "icon2.png", id:"icon" %></label>
      <label><%= radio_button_tag :image, "./app/assets/images/test3.png" %><%= image_tag "icon3.png", id:"icon" %></label>
      <h6 id="m-top">※フレームを選択</h6>
    </div>
    <p class="center" id="m-top"><%= submit_tag "ツイートする", class: "btn btn-info btn-lg"%></p>
    <div>
      <%= image_tag "test1.png", class:"center-block", id:"test1", style:"display: none;" %>
      <%= image_tag "test2.png", class:"center-block", id:"test2", style:"display: none;" %>
      <%= image_tag "test3.png", class:"center-block", id:"test3", style:"display: none;" %>
    </div>
  <% end %>
</div>

<!-- ここからjQuery -->
<script>
$('#image_._app_assets_images_test1.png').on('click', function() {
  $("#test1").show();
  $("#test2").hide();
  $("#test3").hide();
});
$('#image_._app_assets_images_test2.png').on('click', function() {
  $("#test2").show();
  $("#test1").hide();
  $("#test3").hide();
});
$('#image_._app_assets_images_test3.png').on('click', function() {
  $("#test3").show();
  $("#test1").hide();
  $("#test2").hide();
});
</script>
<!-- ここまで -->

  <% else %>
    <%= link_to "登録/ログイン", new_user_session_path, class: "btn btn-info btn-lg btn-block" %>
  <% end %>
</div>