config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :omniauth_callbacks => 'users/omniauth_callbacks',
    :sessions => 'users/sessions',
    :registrations => 'users/registrations'
   }

  # ログアウト
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # root 'static_pages#home'
  root 'tweets#new'
  get 'static_pages/home'
  get 'static_pages/faq'
  get 'static_pages/about'
  get 'static_pages/delete'
  resources :users, only: [:show]
  resources :tweets
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_head.html.erb
<title><%= yield(:title) %> | ついわく</title>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>



<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="css/bootstrap.min.css" rel="stylesheet">
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-159301168-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-159301168-1');
</script>
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/shared/_login.html.erb
<nav class="navbar navbar-default">
  <%= render 'shared/nav_header' %>
  
  <div id="gnavi" class="collapse navbar-collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      <li><%= link_to "退会", static_pages_delete_path %>
    </ul>
  </div>
</nav>

app/views/shared/_login_body.html.erb
<!--Twitterのアイコン画像と名前-->
<div class="center profile">
  <p><%= image_tag current_user.image.sub(/_normal/, ''), id:"user-image" %></p>
    <h4><%= current_user.name %></h4>
  <h5 id="nickname">@<%= current_user.nickname %></h5>

</div>

<ul class="list-group">
	<li class="list-group-item">1.ツイート内容を入力</li>
	<li class="list-group-item">2.フレームを選択</li>
	<li class="list-group-item">3. [ツイートする] ボタンを押す</li>
  <li class="list-group-item">4.ツイート完了！！</li>
</ul>


<!--ツイートの入力フォーム-->
<div class="form-group">
  <%= form_for(@tweet) do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <div><%= f.text_area :comment, rows:"8", class:"form-control js-count", id:"tweet-area", maxlength:"100" %></div>
    <!--文字数カウント-->
    <div class="counter">
      <span class="show-count">0</span>/100
    </div>
    <div class="center" id="m-top">
     <label><%= f.radio_button :image, "./app/assets/images/test1.png" %><%= image_tag "blue.png", id:"icon" %></label>
      <label><%= f.radio_button :image, "./app/assets/images/sample.png" %><%= image_tag "green.png", id:"icon" %></label>
      <label><%= f.radio_button :image, "./app/assets/images/sample1.png" %><%= image_tag "pink.png", id:"icon" %></label>
      <h6 id="m-top">※フレームを選択</h6>
    </div>
         <div>
      <%= image_tag "test1.png", class:"center-block", id:"test1", style:"display: none;" %>
      <ul class="list-group">
        <li class="list-group-item" id="test2", style="display: none; margin: 50px;">ごめんなさい。<br>フレーム準備中です・・・</li>
      </ul>
      <% image_tag "test2.png", class:"center-block", id:"test2", style:"display: none;" %>
      <ul class="list-group">
        <li class="list-group-item" id="test3", style="display: none; margin: 50px;">ごめんなさい。<br>フレーム準備中です・・・</li>
      </ul>
      <% image_tag "test3.png", class:"center-block", id:"test3", style:"display: none;" %>
    </div>
    <p class="center" id="m-top"><%= f.submit "ツイートする", class: "btn btn-info btn-lg" %></p>
  <% end %>
</div>

<!-- ここからjQuery -->
<script>
$(function(){
  $('.js-count').keyup(function(){
    var count = $(this).val().length;
    $('.show-count').text(count);
  });
});

$('#tweet_image_appassetsimagestest1png').on('click', function() {
  $("#test1").show();
  $("#test2").hide();
  $("#test3").hide();
});
$('#tweet_image_appassetsimagessamplepng').on('click', function() {
  $("#test2").show();
  $("#test1").hide();
  $("#test3").hide();
});
$('#tweet_image_appassetsimagessample1png').on('click', function() {
  $("#test3").show();
  $("#test1").hide();
  $("#test2").hide();
});
</script>
<!-- ここまでjQuery -->

app/views/shared/_logout.html.erb
<nav class="navbar navbar-default">
  <%= render 'shared/nav_header' %>
  
  <div id="gnavi" class="collapse navbar-collapse">
    <ul class="nav navbar-nav">
      <li><%=link_to "ログイン", new_user_session_path %></li>
    </ul>
  </div>
</nav>

app/views/shared/_nav_header.html.erb
<div class="navbar-header">
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#gnavi">
    <!--音声ブラウザにメニューがあることを伝えている-->
    <span class="sr-only">メニュー</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <%= link_to "ついわく", root_path, class: "navbar-brand", id: "logo" %>
</div>  